ifneq ($(markdowns),)
_markdowns = $(markdowns)
else
_markdowns = $(wildcard *.md)
endif
_htmls = $(patsubst %.md,%.html,$(_markdowns))

all: htmls
htmls: $(_htmls)

%.html: %.md
	../bin/md2html $< > $@

clean:
	rm -f $(_htmls)
